# COPYRIGHT © ERVIN REMUS RADOSAVLEVICI - ALL RIGHTS RESERVED
# PRIVATE PROPERTY - UNAUTHORIZED MODIFICATION PROHIBITED

[build]
  publish = "dist"
  command = "npm run build:netlify"
  
[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "latest"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Copyright = "ERVIN REMUS RADOSAVLEVICI - ALL RIGHTS RESERVED"
    X-Owner = "Ervin Remus Radosavlevici"
    X-Creator = "Ervin Remus Radosavlevici"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"